### ISSUE TITLE
Provide table of contents in readme

### ISSUE THREAD

**Issue by schittli** [wp-cli/scaffold-package-command#219] opened 2022-11-22 18:03 UTC
**Thank you very much for sharing your great work!**

## Feature Request
- [x] Yes, I reviewed the contribution guidelines

**Describe your use case and the problem you are facing**

If one creates a pdf from `README.md`, then it creates 127 pages. A lot of work!
But this work get's pretty useless, because if someone does not know entity-command, then it's almost impossible to get a useful overview.

**Describe the solution you'd like**

Please, create a table of contents, at least with Header 1, so that users can jump to the interesting chapters like system requirements, setup and commands for comments, menus, options, posts, sites, terms, and users.

Thanks a lot, kind regards,
Thomas

**Comment by swissspidy** [comment] 2023-08-07 10:09
I just transferred this issue to the saffold-package-command repository as it's the more appropriate location given that we can solve the TOC issue with the scaffolding script.

Then I just realized there's already an issue for exactly that, see #141

So I am closing this as a duplicate of #141

**Closed by swissspidy** 2023-08-07 10:09 UTC
Labels: command:scaffold-package-readme, scope:documentation
